### ISSUE TITLE
Error "Unable to generate request for your skill"

### ISSUE THREAD

**Issue by travplan** [tartanguru/alexa-google-search#23] opened 2017-04-19 16:35 UTC
@tartanguru 
I am having a bit of difficulty.
I have gone through the entire process multiple times, and although it seems a success, it doesnt function.
When I test in the "Service Simulator" in my developer console, I get the message "Unable to generate request for your skill" in the Lambda Request window.
When I run the test (as described at the end of the readme, in the AWS Lambda console, i get the following result:
{
  "version": "1.5.2 - German locale fix",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "Welcome to Google Search. What are you searching for?"
    },
    "shouldEndSession": false,
    "reprompt": {
      "outputSpeech": {
        "type": "PlainText",
        "text": "Welcome to Google Search. What are you searching for?"
      }
    }
  },
  "sessionAttributes": {}
}

The skill is listed in my Alexa app and is enabled. When I say "Alexa, Ask Google *something*" it seems to think for a second, and then does nothing.

I really can't find anything that doesnt correspond with the tutorial, or any other people having the same issue as me in any forum I can find.

I do have both the location in Alexa, and the Developer console for this skill set to English US.

Any help or direction would be much appreciated.
Thanks

**Comment by gnomium** [comment] 2017-04-19 21:39
can confirm, i got the same.

**Comment by tartanguru** [comment] 2017-04-20 06:22
Amazon seem to have changed something yesterday that seems to have affected
lots of skills.
There is a thread about this on the amazon developer forums here:-

https://forums.developer.amazon.com/questions/67444/error-unable-to-generate-request-for-your-skill.html

Not much I can do until amazon acknowledge the issue

**Comment by tartanguru** [comment] 2017-04-20 07:49
I don't speak German, but have read the google translated version of the link you posted. It appears that Amazon have made changes to how CUSTOM slots works. I have no idea why changing the sample utterances to German gets over this issue though. The search "wie alt werden hunde" does return a valid response even with the Skill set to UK English:- Dog, Lifespan , 10 – 13 years, although this version of the skill was created a few days ago on lambda.

**Comment by vin047** [comment] 2017-04-20 23:41
Having the same issue myself - using English UK (Ireland region).

Using the service simulator I tried "**capital of england**" as the utterance: Unable to generate request for your skill.

Interestingly, if I try the phrase "**_what is the_ capital of england**", I get a valid service response...

**Comment by tszumowski** [comment] 2017-04-21 02:43
I appear to also be having this same issue now. I tried the same test cases as @vin047 and got the same results.

**Comment by tartanguru** [comment] 2017-04-21 07:25
I've just tried the "capital of england" question with the Version 2 Final release branch and I get a valid response. I am using node 6.10 for this version which might affect the result

**Comment by vin047** [comment] 2017-04-21 10:31
I just tried the "capital of england" test cases with **Version 2 Final** branch, **Node 6.10**, but get the same result as before: 

"capital of england": Unable to generate request for your skill.
"what is the capital of england": valid response

Very strange that its working for you @tartanguru

**Comment by travplan** [comment] 2017-04-21 12:09
I can confirm the same results as @vin047. Version 2 final branch, Node 6.10.
All regions set to North America US, North Viginia.

**Comment by travplan** [comment] 2017-04-21 14:03
@tartanguru @gnomium @vin047 @tszumowski 

Ok, so I've managed to get it working with any question I can think of. Although some utterances aren't able to return a result, nothing I ask fails with an error.
If you paste all of the below sample questions into the "Values" of your custom slot type "SEARCH", all questions, in any format I can think of return a result of some sort.

who is the queen 
why is the sky blue 
how old become dogs 
where is hamburg 
what is christmas 
when is easter 
what are mice
what does bleach do
can you eat grass
is there a god
are bats black
whats the biggest planet
can dolphins swim
did giraffes go extinct
do porcupines sleep
whats two plus two
will bees be killed
could a woodchuck chuck wood
could flamingos fly
are oceans wet
are trees big
does korea have nukes
should you drink milk
should trucks smoke

If you find a question that returns an error, just add it to the list, save it, and it will then work.
I would suggest to come back here and paste your additions so we have a more complete working model, as I'm sure I've missed a bunch.

I don't know if this is the total answer, but it is working.

**Comment by tszumowski** [comment] 2017-04-21 15:14
@travplan That seemed to help performance a lot.

**Comment by tartanguru** [comment] 2017-04-21 20:28
Thanks for this - this certainly makes the recognition better. Hopefully Amazon will fix the issue soon.
Interestingly this goes against amazons advice:-

"If you’re still not getting the results, trying setting the CatchAll values to around twenty 2 to 8 word random phrases (from a random word generator – be really random). When the user says something that matches your other utterances, those intents will still be sent. When it doesn’t match any of those, it will fall to the CatchAll slot. If you go this route, you’re going to lose accuracy because you’re not taking full advantage of Alexa’s NLP so you’ll need to test heavily."

This is the list I am using:-

who is the queen
why is the sky blue
how old become dogs
where is hamburg
what is christmas
when is easter
what are mice
what does bleach do
can you eat grass
is there a god
are bats black
whats the biggest planet
can dolphins swim
did giraffes go extinct
do porcupines sleep
whats two plus two
will bees be killed
could a woodchuck chuck wood
could flamingos fly
are oceans wet
are trees big
does korea have nukes
should you drink milk
should trucks smoke
capital of new york
inventor of television
what time does costco close
how far away is the moon
how many oceans are there
who are the presidents children
why do stars suddenly appear

**Comment by tartanguru** [comment] 2017-04-21 22:32
Amazon have now confirmed that this is an issue at there end:-

https://forums.developer.amazon.com/questions/67444/error-unable-to-generate-request-for-your-skill.html

**Comment by tartanguru** [comment] 2017-04-27 18:50
It appears that Amazon have addressed this issue as per here:-

https://forums.developer.amazon.com/questions/68881/utterance-with-just-the-slot.html

"We recently made new tools available to help with the creation and testing
of skills. The new features inadvertently impacted a small number of
skills. We fixed the issue yesterday and all live skills should work as
expected. Please post here if you have any more issues and we will monitor
and provide assistance. For skills in development, you can now resolve this
issue by clicking ‘Save’ on the interaction model tab or by clicking Build
Model in Skill Builder (beta). We apologize for the inconvenience."

**Comment by travplan** [comment] 2017-04-27 19:51
I can confirm that Amazon's update worked.

I returned the sample utterances to the original "who is the queen" and "why is the sky blue" only, then clicked save. The console rebuilt the interaction model, and now I cannot get a question that fails in the test simulator.
All questions return a response, even if sometimes the response returned is "I’m sorry, I wasn't able to find an answer."

Looks to me like all is well.

**Comment by vin047** [comment] 2017-04-27 19:56
@travplan or @tartanguru any indication on which approach is better? The long list of sample utterances VS original two?

**Comment by tartanguru** [comment] 2017-05-11 11:56
I don't think it really makes any difference although amazon only recommend between sample 2-8 phrases. With that in mind I'm going to revert to the old list so that it aligns with the guides circulating around.
Closing issue

**Closed by tartanguru** 2017-05-11 11:56 UTC
